name: epic_hire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-70.0.dev

dependencies:
  bitsdojo_window: ^0.1.6
  cached_network_image: ^3.4.1
  chiclet: ^1.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  get_time_ago: ^2.3.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  haptic_feedback: ^0.5.1+1
  hive_ce: ^2.10.1
  http: ^1.3.0
  pdfrx: ^1.1.19
  riverpod_annotation: ^2.6.1
  story: ^1.1.0
  universal_platform: ^1.1.0
  uuid: ^4.5.1
  wrapper:
    path: packages/wrapper

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5


flutter:
  uses-material-design: true
  assets:
    - assets/icons/